def dog(name)
  return name
end

def cat(name)
  return name
end

puts "The dog's name is #{dog('Spot')}."

puts "The cat's name is #{cat("Ginger")}."

# error that used to exist is EXACTLY what i thought. passed 1 argument when code was expecting 0

# gud